In [1]:
import pandas as pd
import numpy as np

In [2]:
# ## 1. create the following two dimensional arrays

# [[1., 0., 0., 0., 0.],
#        [0., 1., 0., 0., 0.],
#        [0., 0., 1., 0., 0.],
#        [0., 0., 0., 1., 0.],
#        [0., 0., 0., 0., 1.]]
# 2. [[1, 0, 0, 0],
#        [0, 2, 0, 0],
#        [0, 0, 3, 0],
#        [0, 0, 0, 4]]
# 3. Create a checkerboard pattern in an array using row and col slicing


Question 1.1: Create an array with below pattern
    
        [[1., 0., 0., 0., 0.],
    
        [0., 1., 0., 0., 0.],

        [0., 0., 1., 0., 0.],

        [0., 0., 0., 1., 0.],

        [0., 0., 0., 0., 1.]]

In [3]:
#Method 1: Using identity function of numpy
arr1=np.identity(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
#Method 2: Using for loop
arr1=np.zeros([5,5])
array_shape = arr1.shape
rows = array_shape[0]
cols = array_shape[1]
for r in range(0,rows):
    for c in range(0,cols):
        if(r==c):
            arr1[r,c] = 1
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Question 1.2: Create an array with below pattern
    
        [[1, 0, 0, 0],
          
        [0, 2, 0, 0],
        
        [0, 0, 3, 0],
        
        [0, 0, 0, 4]]

In [5]:
#Method 1: Using diag function of numpy
arr2= np.diag((1,2,3,4))
arr2

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [6]:
# Method 2: Using for loop
arr2=np.full([4,4],0)
array_shape = arr1.shape
rows = array_shape[0]
cols = array_shape[1]
for r in range(0,rows-1):
    for c in range(0,cols-1):
        if(r==c):
            arr2[r,c] = r+1
arr2

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Question 1.3: 3. Create a checkerboard pattern in an array using row and col slicing


In [7]:
#Creating a checkerboard pattern using Slicing so that alternative elemement is assigned as 1

arr3=np.zeros([8,8], dtype='int32')
arr3[::2,::2]=1
arr3[1::2,1::2]=1
arr3

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

4. Compute the no of bytes occupied in the memory for an array of numbers from 1 to 10

In [8]:
#Using nbytes function of numpy array to find out the bytes occupied in memory for a given array
arr4=np.arange(1,11)
print("Bytes Occupied in memory by given array is: ", arr4.nbytes)


Bytes Occupied in memory by given array is:  80


### 5. img=[[200,210,209],[213,0,214],[214,215,217]]


Given a snap shot of the image, estimate the centre pixel with mean,median values.


In [28]:
img=np.array([[200,210,209],[213,0,214],[214,215,217]])
plane_img=img.ravel()
img[1,1]=np.mean(plane_img)
print("Center pixel value replaced with mean:\n", img) 
# Mean value 188 seems to be very less compated other elements in the image array so need to apply median
img[1,1]=np.median(plane_img)
print("\nCenter pixel value replaced with median:\n",img)
# Median value 213 proves to appropriate value for the given location. 


Center pixel value replaced with mean:
 [[200 210 209]
 [213 188 214]
 [214 215 217]]

Center pixel value replaced with mendia:
 [[200 210 209]
 [213 213 214]
 [214 215 217]]


6. create a Pandas series to store the marks of students and filter the marks >50,>70,>90

In [10]:
arr6 = np.random.randint(0,100, size =(20))
marks = pd.Series(arr6)
print("Marks greater than 50:\n", marks[marks>50])
print("\n\nMarks greater than 75:\n", marks[marks>70])
print("\n\nMarks greater than 90:\n", marks[marks>90])

Marks greater than 50:
 2     74
9     85
13    53
18    96
19    82
dtype: int64


Marks greater than 75:
 2     74
9     85
18    96
19    82
dtype: int64


Marks greater than 90:
 18    96
dtype: int64


7.Create data frame given below to store student info from the numpy arrays defined

In [11]:
name=np.array(['kevin','john','hari'])
age=np.array([23,21,22])
gender=np.array(['m','m','f'])
state=np.array(['TN','KL','KN'])
cgpa=np.array([9,8,7])

df=pd.DataFrame({'name':name,'age':age,'gender':gender,'state':state,'cgpa':cgpa})
df

name  age gender state  cgpa
0  kevin   23      m    TN     9
1   john   21      m    KL     8
2   hari   22      f    KN     7

    1.Filter the age
    
    2.filter age,cgpa
    
    3.Filter age>22
    
    4.names starts with j
    
    5.names contains 'n'

In [12]:
#1.Filter the age
df_age=df['age']
df_age

0    23
1    21
2    22
Name: age, dtype: int64

In [13]:
#2.filter age,cgpa
df_age_cgpa=df[['age','cgpa']]
df_age_cgpa

age  cgpa
0   23     9
1   21     8
2   22     7

In [14]:
#3.Filter age>22
df_age_check=df[df['age']>22]
df_age_check

name  age gender state  cgpa
0  kevin   23      m    TN     9

In [15]:
#4.names starts with j
print(df['name'][df['name'].str.startswith('j')])


1    john
Name: name, dtype: object


In [16]:
#5.names contains 'n'
print(df['name'][df['name'].str.contains('n')])

0    kevin
1     john
Name: name, dtype: object


8. Given the two data frames,

dfr1=pd.DataFrame({'Id':[1,2,3,5,9],

                    'Col1':[1,2,3,4,5],
                    
                     'col2':[6,7,8,9,10],
                     
                      'col4':['apple','orange','banana','strawberry','rasberry']})
                      
  dfr2=pd.DataFrame({'Id':[1,1,3,5],
  
                    'ColA':[8,9,10,11],
                    
                     'colB':[12,13,15,17],
                     
                      'col4':['apple','orange','banana','kiwi']})
                      

Perform left, right and inner join on the dataframes

In [17]:
dfr1=pd.DataFrame({'Id':[1,2,3,5,9],
                'Col1':[1,2,3,4,5],
                
                 'col2':[6,7,8,9,10],
                 
                  'col4':['apple','orange','banana','strawberry','rasberry']})
                  
dfr2=pd.DataFrame({'Id':[1,1,3,5],
                'ColA':[8,9,10,11],
                
                 'colB':[12,13,15,17],
                 
                  'col4':['apple','orange','banana','kiwi']})



In [18]:
dfr1

Id  Col1  col2        col4
0   1     1     6       apple
1   2     2     7      orange
2   3     3     8      banana
3   5     4     9  strawberry
4   9     5    10    rasberry

In [19]:
dfr2

Id  ColA  colB    col4
0   1     8    12   apple
1   1     9    13  orange
2   3    10    15  banana
3   5    11    17    kiwi

In [20]:
#Left Join
dfr1.join(dfr2, how='left', lsuffix="_L", rsuffix="_R")

Id_L  Col1  col2      col4_L  Id_R  ColA  colB  col4_R
0     1     1     6       apple   1.0   8.0  12.0   apple
1     2     2     7      orange   1.0   9.0  13.0  orange
2     3     3     8      banana   3.0  10.0  15.0  banana
3     5     4     9  strawberry   5.0  11.0  17.0    kiwi
4     9     5    10    rasberry   NaN   NaN   NaN     NaN

In [21]:
#Right Join
dfr1.join(dfr2, how='right', lsuffix="_L", rsuffix="_R")

Id_L  Col1  col2      col4_L  Id_R  ColA  colB  col4_R
0     1     1     6       apple     1     8    12   apple
1     2     2     7      orange     1     9    13  orange
2     3     3     8      banana     3    10    15  banana
3     5     4     9  strawberry     5    11    17    kiwi

In [22]:
#Inner Join
dfr1.join(dfr2, how='inner', lsuffix="_L", rsuffix="_R")

Id_L  Col1  col2      col4_L  Id_R  ColA  colB  col4_R
0     1     1     6       apple     1     8    12   apple
1     2     2     7      orange     1     9    13  orange
2     3     3     8      banana     3    10    15  banana
3     5     4     9  strawberry     5    11    17    kiwi

9. Apply sigmoid function to the array [2,5,6]

1.define sigmoid function

2.create the np array

3.Apply the function to the array

In [23]:
# 1. Defining Sigmoid function
def sigmoid_function(x):
    return(1/(1+np.exp(-x)))
    

In [24]:
# 2. Numpy array Creation
arr9=np.array([2,5,6])
arr9

array([2, 5, 6])

In [25]:
# 3. Applying the Sigmoid function to the array
sigmoid_function(arr9)

array([0.88079708, 0.99330715, 0.99752738])