In [2]:
import numpy as np

In [2]:
my_array1 = np.random.random(size =(3,2,2))
my_array1

array([[[0.43924319, 0.8129108 ],
        [0.78996567, 0.18715918]],

       [[0.71732521, 0.07087143],
        [0.09267353, 0.61180062]],

       [[0.29809067, 0.48971532],
        [0.79473565, 0.56822322]]])

In [3]:
my_array2 = np.random.randint(1,20, size =(4,5))
my_array2

array([[ 2, 17, 19, 19,  1],
       [ 5,  9,  9,  7,  9],
       [ 9, 16, 18,  4, 19],
       [ 3, 10,  1,  3, 15]])

In [4]:
my_array3 = np.arange(start = 0, stop = 40, step = 5)
my_array3

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [5]:
my_array4 = np.array([(11,32,23),(34,55,46)])
print(my_array4)
print(my_array4.ndim)

[[11 32 23]
 [34 55 46]]
2


In [6]:
array5 = np.random.randint(1,20, [4,5,7])
print(array5)
print(array5.ndim)
print(array5.size)
print(array5.shape)

[[[18 13  4  1 11  4  1]
  [16 10  1 10 14  7 12]
  [13 18 17  5 19  4  5]
  [13  4 16  2  2 19  7]
  [15 19  2 12 14  7 12]]

 [[ 9 12 17 11 13 10  1]
  [11  2  2 16  7  9 13]
  [ 4  1 13  7 12  7  7]
  [15 15  4 14 17  3 11]
  [ 8  4 14 19  9 15 19]]

 [[ 9  4  9  8  8 13 13]
  [ 5  1  8 16 17  8 16]
  [ 7 13  7 16 10 17 15]
  [16  4 17  8  7 13 16]
  [15 15  7  6 14  1  1]]

 [[ 2  6  2 14 14 13  3]
  [ 3 12  8  6 18  7 12]
  [ 2 16  2  7  1  6  8]
  [11 12  4  3  1  5 10]
  [18 12  8 12 16  8 17]]]
3
140
(4, 5, 7)


In [7]:
array6 = np.array([(1,2,3,4,5,6)])
print(array6)
print(array6.size)
print(array6.shape)
print(array6.ndim)

[[1 2 3 4 5 6]]
6
(1, 6)
2


In [8]:
array7 = np.array([(8,9,10),(11,12,13)])
print(array7)
#array7 = array7.reshape([2])
print(array7)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9 10]
 [11 12 13]]


In [9]:
array 8 = np.array([[101,231,321,[412,,512,622,],[544,321,456]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1311586572.py, line 1)

In [12]:
array24 = np.random.randint(1,20, [4,5])
print(array24)
print(array24.ndim)
print(array24.size)
print(array24.shape)

[[19  5 17  7  1]
 [13 18 11  6  5]
 [15  3  4 10 10]
 [12 16 14  4 18]]
2
20
(4, 5)


In [13]:
print(array9[[2],[2],[2]])
print(array9[2][1])

NameError: name 'array9' is not defined

In [14]:
my_array10 = np.array([(11,32,23),(34,55,46)])
print(my_array10)
print(my_array4.ndim)

[[11 32 23]
 [34 55 46]]
2


In [15]:
my_array10[1][1]

55

In [16]:
my_array4 = np.zeros(5)

In [17]:
my_array4

array([0., 0., 0., 0., 0.])

In [18]:
my_array11 = np.array([(45,54,67),(55,33,66)])

In [19]:
my_array11

array([[45, 54, 67],
       [55, 33, 66]])

In [20]:
my_array_add = my_array10+my_array11
print(my_array_add)

[[ 56  86  90]
 [ 89  88 112]]


In [ ]:
my_array_add = my_array_add+3

In [21]:
my_array_add

array([[ 56,  86,  90],
       [ 89,  88, 112]])

In [22]:
my_array12 = my_array_add >= 90
my_array12

array([[False, False,  True],
       [False, False,  True]])

In [ ]:
my_array13 = my_array_add[my_array12]
my_array13

In [ ]:
my_array14 = my_array_add[my_array_add >= 90]
my_array14

2D arrays

# 2D arrays

In [23]:
my_array21 = np.array([(11,32,23),(34,55,46)])
my_array22 = np.array([(45,54,67),(55,33,66)])

In [24]:
my_array21*my_array22

array([[ 495, 1728, 1541],
       [1870, 1815, 3036]])

In [25]:
my_array23= my_array21*2
my_array23

array([[ 22,  64,  46],
       [ 68, 110,  92]])

In [26]:
my_array23.sum()


402

In [27]:
print(my_array21)
print('axis = 0', my_array21.sum(axis = 0))
print('axis = 1',  my_array21.sum(axis = 1))

[[11 32 23]
 [34 55 46]]
axis = 0 [45 87 69]
axis = 1 [ 66 135]


In [1]:
array24 = np.random.randint(1,20, [2,3,4,5])
print(array24)
print(array24.ndim)
print(array24.size)
print(array24.shape)
print('axis = 0', array24.sum(axis = 0))
print('axis = 1',  array24.sum(axis = 1))
print('axis = 2',  array24.sum(axis = 2))
print('axis = 3',  array24.sum(axis = 3))

NameError: name 'np' is not defined

In [29]:
my_array21 = np.array([(11,32,23),(34,55,46)])
my_array22 = np.array([(45,54,67),(55,33,66)])

print(my_array21)
print(my_array22)

[[11 32 23]
 [34 55 46]]
[[45 54 67]
 [55 33 66]]


In [30]:
np.concatenate([my_array21,my_array22])


array([[11, 32, 23],
       [34, 55, 46],
       [45, 54, 67],
       [55, 33, 66]])

In [31]:
np.concatenate([my_array21,my_array22],axis=1)

array([[11, 32, 23, 45, 54, 67],
       [34, 55, 46, 55, 33, 66]])

In [32]:
my_array21 = np.arange(12)
print(my_array21)
for i in my_array21:
    print(i+10)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
10
11
12
13
14
15
16
17
18
19
20
21


In [33]:
array25 = np.random.randint(1,20, [4,5])
print(array25)
print(array25.ndim)
print(array25.size)
print(array25.shape)

[[10 10  8 12 19]
 [15  1  5 12 13]
 [ 9  7 18 17  6]
 [ 3 13 12  8 17]]
2
20
(4, 5)


In [34]:
for i in array25:
    print(i+10)

[20 20 18 22 29]
[25 11 15 22 23]
[19 17 28 27 16]
[13 23 22 18 27]


In [ ]:
my_array21 = np.random.randint(1,20,[2,3])
print (my_array21)
for i in my_array21:
    print(i,i+102)
    print('new')
    
for i in my_array21:
    for j in i:
        print(j, j+102)
        print('next row')

In [ ]:
pip install panda

In [ ]:
import pandas as pd
from pandas.core.arrays.sparse import SparseArray as _SparseArray

In [ ]:
numbers = range(1,100,5)
pd.Series(numbers)

In [ ]:
data = {'Maths':60, 'Science':89, 'English': 76, 'Social Science': 86}
ser1 = pd.Series(data)

In [ ]:
subjects= ['Maths', 'Science', 'English', 'Social Science', 'Arts']
ser1

In [ ]:
ser1.isnull()

In [ ]:
ser1.isnull().sum()

In [ ]:
ser1['Science'] = 56

In [ ]:
ser1

In [ ]:
ser1.Maths == 74

In [ ]:
ser1.Maths

In [ ]:
ser1.index

In [ ]:
ser1.index.name = 'Subject'

In [ ]:
ser1

In [ ]:
ser1+5

In [ ]:
import numpy as np
num = pd.Series(np.random.random(15)*10).round()
num

In [ ]:
square = pd.Series(num*num)
square.index = [num]
square

In [ ]:
square.name = 'Square'
square.index.name = "Number"
square

In [ ]:
square.info()

In [ ]:
type(square)

In [ ]:
type(square)

In [ ]:
square.index

In [ ]:
square

In [ ]:
square.iloc[3]

In [ ]:
square.loc[8]

In [ ]:
square.sort_values()

In [ ]:
ser1.sort_index()


In [ ]:
ser1.sort_values()
